sonar.projectKey=__PROJECT_NAME__-backend
sonar.projectName=__PROJECT_NAME__ Backend
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=tests

sonar.exclusions=**/.venv/**,**/node_modules/**,**/dist/**,**/htmlcov/**,**/__pycache__/**

sonar.python.version=3.14
sonar.python.coverage.reportPaths=coverage.xml
